# Setup

title:            'Wildside'
description:      'Hi! I’m Edmundo, web designer and weekend wanderer living in lovely Dublin, Ireland. This blog is a diary of my stories and adventures.'

url:              http://edmundojr.com
baseurl:          '/wildside'

permalink:        :title/

paginate:         5
paginate_path:    '/wildside/blog/page:num/'

author:
  name:           'Edmundo Santos'
  email:          hello@edmundojr.com
  facebook:       edmundojr
  github:         edmundojr
  instagram:      edmundojr_
  stackoverflow:  users/1034869/edmundojr
  twitter:        edmundojr_

analytics:

disqus:           edmundojr

# Dependencies

markdown:         redcarpet

exclude:          ['Gruntfile.js', 'package.json', 'node_modules', 'assets/scss']
keep_files:       ['_site/assets/css']