# Setup

title:            'Wildside'
description:      'Hi! I’m Edmundo, designer, developer, and weekend wanderer living in lovely Dublin, Ireland. This blog is a photo diary of my stories and adventures.'

url:              http://edmundojr.com
baseurl:          '/wildside'

permalink:        :title/

sass:
  sass_dir:       assets/styles/

gems:             [jekyll-paginate]

paginate:         5
paginate_path:    '/wildside/blog/page:num/'

author:
  name:           'Edmundo Santos'
  email:          hello@edmundojr.com
  facebook:       edmundojr
  github:         edmundojr
  instagram:      edmundojr_
  stackoverflow:  users/1034869/edmundojr
  twitter:        edmundojr_

analytics:        1068613-21

disqus:           edwildside
